producers/urls.py
from django.conf.urls import url
from django.contrib.flatpages import views as flatpages_views
from django.views.generic import TemplateView

from . import views


urlpatterns = [
    url(r'^$',
        views.HomeView.as_view(),
        name='home'),

    # We add Flatpages here, rather than use the middleware, so that we can
    # easily link to a Flatpage by name in the templates.
    url(r'^about/$',
        flatpages_views.flatpage, {'url': '/about/'}, name='about'),

    # So we can test these templates when DEBUG=True.
    url(r'^404/$', TemplateView.as_view(template_name='404.html')),
    url(r'^500/$', TemplateView.as_view(template_name='500.html')),

    url(r'^map/$',
        views.MapView.as_view(),
        name='producers_map'),

    url(r'^producer/add/$',
        views.ProducerAddView.as_view(),
        name='producer_add'),

    url(r'^producer/add/thanks/$',
        flatpages_views.flatpage,
        {'url': '/producer/add/thanks/'},
        name='producer_add_thanks'),

    url(r'^producer/(?P<pk>\d*)/$',
        views.ProducerDetailView.as_view(),
        name='producer_detail'),
]

producers/models.py
import logging

from django.contrib.gis import geos
from django.contrib.gis.db import models
from django.urls import reverse
# From https://stackoverflow.com/a/48894881/250962:
from django.db.models import Manager as GeoManager
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.forms.models import model_to_dict

from imagekit.models import ImageSpecField
from imagekit.processors import Adjust, ResizeToFit

from . import managers
from .postcoder import Postcoder, PostcoderException
from .validators import validate_uk_phone_number, validate_uk_postcode


logger = logging.getLogger(__name__)


class TimeStampedModelMixin(models.Model):
    "Should be mixed in to all models."

    time_created = models.DateTimeField(auto_now_add=True,
                help_text="The time this item was created in the database.")
    time_modified = models.DateTimeField(auto_now=True,
                help_text="The time this item was last saved to the database.")

    class Meta:
        abstract = True


class Product(TimeStampedModelMixin, models.Model):
    name = models.CharField(blank=False, null=False, max_length=30)
    slug = models.SlugField(blank=False, null=False, max_length=30,
            unique=True, help_text="Used in URLs referring to this product.")
    order = models.PositiveSmallIntegerField(blank=False, null=False,
            default=10,
            help_text="Products are ordered by this number.")

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['order']


class ProducerImage(TimeStampedModelMixin, models.Model):
    "The images that can be attached to Producers. Uploaded by users."

    producer = models.ForeignKey('Producer', on_delete=models.CASCADE, related_name='images')

    image = models.ImageField(upload_to='producers')

    image_thumbnail = ImageSpecField(source='image',
                        processors=[
                            ResizeToFit(100, 100, upscale=True),
                            Adjust(sharpness=2.0)
                        ],
                        format='JPEG',
                        options={'quality': 60})

    image_medium = ImageSpecField(source='image',
                        processors=[
                            ResizeToFit(500, 400, upscale=False),
                            Adjust(sharpness=2.0)
                        ],
                        format='JPEG',
                        options={'quality': 80})

    objects = models.Manager()

    class Meta:
        ordering = ['-time_created']

    def get_absolute_url(self):
        return self.image.url


class Producer(TimeStampedModelMixin, models.Model):

    business_name = models.CharField(blank=False, null=False, max_length=255)
    contact_name = models.CharField(blank=True, null=False, max_length=255)
    postcode = models.CharField(blank=False, null=False,
                            validators=[validate_uk_postcode], max_length=8)
    phone = models.CharField(blank=False, null=False,
                        validators=[validate_uk_phone_number], max_length=15)
    email = models.EmailField(blank=False, null=False)
    url = models.URLField(blank=True, null=False, verbose_name="URL")

    # Set with the set_location() function, below.
    point = models.PointField(srid=4326, blank=True, null=True)

    is_visible = models.BooleanField(default=False,
            help_text="Check box to make this Producer visible on the site.")

    products = models.ManyToManyField(Product)

    objects = GeoManager()

    # Only producers with is_visible=True:
    visible_objects = managers.VisibleProducersManager()

    def __str__(self):
        return self.business_name

    def save(self, *args, **kwargs):
        #self.point = Point(self.longitude, self.latitude)
        self.postcode = self.postcode.strip().upper()
        super().save(*args, **kwargs)

    class Meta:
        ordering = ['-time_created']

    @property
    def latitude(self):
        return self.point.y if self.point else 0

    @property
    def longitude(self):
        return self.point.x if self.point else 0

    def get_absolute_url(self):
        return reverse('producer_detail', kwargs={'pk': self.pk})


@receiver(pre_save, sender=Producer)
def set_location(sender, instance, **kwargs):
    """
    Tries to set the lat/lon of the Producer when it's saved, based on the
    postcode.

    If the postcode has changed, or Producer is brand new, we look up lat/lon.

    If found, we set the Producer.point value.

    If we can't find lat/lon we set Producer.point to None.
    """

    set_point = False

    try:
        obj = sender.objects.get(pk=instance.pk)
    except sender.DoesNotExist:
        # Object is new.
        set_point = True
    else:
        if not obj.postcode == instance.postcode:
            # Postcode has changed.
            set_point = True

    if set_point:
        try:
            latlon = Postcoder().geolocate(instance.postcode)
            point = "POINT(%s %s)" % (latlon['longitude'], latlon['latitude'])
            instance.point = geos.fromstr(point)
        except PostcoderException as e:
            logger.error('Error trying to geolocate "%s": %s' % \
                                                (instance.postcode, str(e)))
            # Unset whatever's there.
            instance.point = None

producers/forms.py
from django import forms
from django.conf import settings
from django.contrib.gis.geos import Point
from django.forms import inlineformset_factory

from captcha.fields import ReCaptchaField

from . import validators
from .models import Producer, ProducerImage, Product


attrs = {'class': 'form-control'}
required_attrs = {'class': 'form-control', 'required': 'required',}
postcode_attrs = {k:v for k,v in required_attrs.items()}
postcode_attrs['class'] = postcode_attrs['class'] + ' form-control-postcode'


class HoneypotFormMixin(forms.Form):
    "Provides a hidden field designed to prevent automated posting."
    honeypot = forms.CharField(required=False,
                            label='If you enter anything in this field '\
                                'your data will be treated as spam')

    def clean_honeypot(self):
        """Check that nothing's been entered into the honeypot."""
        value = self.cleaned_data["honeypot"]
        if value:
            raise forms.ValidationError(self.fields["honeypot"].label)
        return value


class FindProducerForm(HoneypotFormMixin, forms.Form):
    postcode = forms.CharField(required=True, max_length=8,
                                widget=forms.TextInput(attrs=postcode_attrs))

    def clean_postcode(self):
        """Check postcode validity, as a format."""
        value = self.cleaned_data["postcode"]
        if value:
            validators.validate_uk_postcode(value)
        return value.strip()


class ProducerForm(HoneypotFormMixin, forms.ModelForm):
    products = forms.ModelMultipleChoiceField(queryset=Product.objects.all())

    class Meta:
        model = Producer
        # The order the fields will appear in the form:
        fields = ['business_name', 'postcode', 'contact_name',
                    'phone', 'email', 'url', 'products', ]

        # Adding attributes to the form fields.
        widgets = {
            'business_name':    forms.TextInput(attrs=required_attrs),
            'contact_name':     forms.TextInput(attrs=attrs),
            'postcode':         forms.TextInput(attrs=postcode_attrs),
            'phone':            forms.TextInput(attrs=required_attrs),
            'email':            forms.EmailInput(attrs=required_attrs),
            'url':              forms.URLInput(attrs=required_attrs),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # For some reason need to do this to use checkboxes for Products:
        # via http://www.joshuakehn.com/2013/6/23/django-m2m-modelform.html
        self.fields['products'].help_text = 'This has to be food you make in the country and do not import'
        self.fields['products'].widget = forms.widgets.CheckboxSelectMultiple()
        self.fields['products'].queryset = Product.objects.all()

        if settings.USE_RECAPTCHA:
            self.fields['captcha'] = ReCaptchaField(label="Anti-spam test")

    def clean_postcode(self):
        value = self.cleaned_data['postcode']
        if value:
            validators.validate_uk_postcode(value)
        return value.strip()

    def clean_phone(self):
        value = self.cleaned_data['phone']
        if value:
            validators.validate_uk_phone_number(value)
        return value.strip()


class ProducerAdminForm(ProducerForm):
    """
    A variation of the Producer form that only Admin users see, which has
    no captcha field and automatically sets the Producer to visible.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if 'captcha' in self.fields:
            del self.fields['captcha']

    def clean_products(self):
        v = self.cleaned_data['products']
        print(v)
        return v

    def save(self, commit=True):
        "Set `is_visible` to be true if added by an Admin."

        m = super().save(commit=False)
        m.is_visible = True

        if commit:
            m.save()
            self._save_m2m()

        return m


# For the part of the Producer form that lists 3 upload fields for images.
ProducerImageFormset = inlineformset_factory(Producer, ProducerImage,
                                                fields=('image',), max_num=3 )

producers/views.py
from django.conf import settings
from django.contrib.flatpages.models import FlatPage
from django.contrib.gis import geos, measure
from django.contrib.gis.db.models.functions import Distance
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import DetailView, FormView, ListView, TemplateView
from django.utils.decorators import method_decorator
from django.utils.http import urlencode
from django.utils.safestring import mark_safe
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect

from .forms import ProducerForm, ProducerAdminForm, FindProducerForm, ProducerImageFormset
from .models import Producer

from . import validators
from .postcoder import Postcoder, PostcoderException


class FlatPageMixin(object):
    """
    Retrieves the FlatPage object for the specified url, and includes it in the
    context.

    If no url is specified, request.path is used.

    From https://blog.schwuk.com/2013/02/26/flatpages-content-in-other-views/
    """
    url = None

    def get_context_data(self, **kwargs):
        if not self.url:
            self.url = self.request.path

        context = super().get_context_data(**kwargs)
        try:
            flatpage = FlatPage.objects.get(url=self.url)
            flatpage.title = mark_safe(flatpage.title)
            flatpage.content = mark_safe(flatpage.content)
            context["flatpage"] = flatpage
        except FlatPage.DoesNotExist:
            context["flatpage"] = None

        return context


class HomeView(FlatPageMixin, ListView):
    "Uses content from a Flatpage."

    template_name = 'producers/home.html'
    model = Producer
    queryset = Producer.visible_objects.all()
    paginate_by = 20


@method_decorator([csrf_protect, never_cache], name='dispatch')
class ProducerAddView(FormView):
    template_name = 'producers/producer_add.html'
    success_url = reverse_lazy('producer_add_thanks')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'image_formset' not in context:
            context['image_formset'] = ProducerImageFormset()

        # If there was an error, the image upload fields don't have their
        # previous values attached. So the best we can do is to notice when
        # images were submitted, and mention this in the template.
        context['num_images_submitted'] = len(self.request.FILES)

        return context

    def get_form_class(self):
        """
        Returns the form class to use in this view
        """
        if self.request.user.is_superuser:
            return ProducerAdminForm
        else:
            return ProducerForm

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        image_formset = ProducerImageFormset(request.POST, request.FILES)

        if form.is_valid() and image_formset.is_valid():
            return self.form_valid(form, image_formset)
        else:
            return self.form_invalid(form, image_formset)

    def form_valid(self, form, image_formset):
        "Both form and formset are valid, so save them."
        producer = form.save()
        image_formset.instance = producer
        img = image_formset.save()

        if producer.is_visible:
            # Presumably added by an admin, so we can see it:
            return HttpResponseRedirect(reverse_lazy('producer_detail',
                                                    kwargs={'pk': producer.pk}))
        else:
            # Added by a normal user, so not visible yet:
            return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, image_formset):
        return self.render_to_response(self.get_context_data(
                                    form=form, image_formset=image_formset))


@method_decorator([csrf_protect, never_cache], name='dispatch')
class MapView(FormView):
    template_name = 'producers/find.html'
    form_class = FindProducerForm

    # We'll look for Producers within this many kilometres:
    max_km = 40

    def get_initial(self):
        "If we have pc=blah in the URL, use that as the default in the form."
        initial = super().get_initial()
        pc = self.request.GET.get('pc', None)
        if pc:
            initial['postcode'] = pc
        return initial

    def get_success_url(self):
        pc = self.request.POST.get('postcode', None)
        if pc:
            getstr = urlencode({'pc': pc})
            return '%s?%s' % (reverse_lazy('producers_map'), getstr)
        else:
            return reverse_lazy('producers_map')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Includes the map JS:
        context['include_map'] = True
        context['max_km'] = self.max_km

        pc = self.request.GET.get('pc')
        if pc:
            pc = pc.upper().strip()
            try:
                validators.validate_uk_postcode(pc)
                context['postcode'] = pc
                producers_context = self.get_producers_context(pc)
                # Combine the two dicts, python 3.5 way:
                context = {**context, **producers_context}
            except:
                # Postcode didn't validate.
                pass
        return context

    def get_producers_context(self, postcode):
        """
        Tries to geocode the postcode, then fetch Producers near to that.

        Returns a dict containing:
            producers: Empty list or a queryset.
            geolocation_error: String, if something went wrong.

        Additionally, if we geocoded successfully:
            latitude: Of the postcode
            longitude: Of the postcode
        """

        context = {
            'producers': [],
        }

        try:
            latlon = Postcoder().geolocate(postcode)
        except PostcoderException as e:
            context['geolocation_error'] = "We couldn't find the location of the postcode '%s'." % postcode
            return context

        # Make a point where this postcode is:
        point = 'POINT(%s %s)' % (latlon['longitude'], latlon['latitude'])
        center = geos.fromstr(point)

        # How far away do we fetch?
        dist = {'km': self.max_km}

        # Get the producers within dist:
        producers = Producer.objects.filter(
                            point__distance_lte=(center, measure.D(**dist)))

        # Add a 'distance' property to them, showing distance from center:
        producers = producers.annotate(distance=Distance('point', center))
        producers = producers.order_by('distance')

        context['latitude'] = latlon['latitude']
        context['longitude'] = latlon['longitude']
        context['producers'] = producers

        return context


class ProducerDetailView(DetailView):
    model = Producer
    queryset = Producer.visible_objects

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Includes the map JS:
        context['include_map'] = True
        return context

producers/templates/producers/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>{% block head_title %}{% block title %}{% endblock %} ({{ site_name }}){% endblock %}</title>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/css/bootstrap.min.css" integrity="sha384-MIwDKRSSImVFAZCVLtU0LMDdON6KVCrZHyVQQj6e8wIEJkW4tvwqXrbMIya1vriY" crossorigin="anonymous">

        {% load static %}
        <link rel="stylesheet" href="{% static "css/styles.css" %}">

        {% if include_map and MAPBOX_API_KEY %}
            <script src='https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.js'></script>
            <link href='https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.css' rel='stylesheet' />
        {% endif %}

        {% block head_extra %}
        {% endblock %}
    </head>
    <body>
        <a href="#content" class="sr-only sr-only-focusable">Skip to main content</a>

        {% if user.is_superuser %}
            <nav class="navbar navbar-full navbar-light bg-faded">
				{% if url_name == 'producer_detail' %}
					<ul class="nav navbar-nav">
						<li class="nav-item">
							<a class="nav-link" href="{% url 'admin:producers_producer_change' producer.id %}">Edit this producer</a>
						</li>
					</ul>
				{% endif %}
                <ul class="nav navbar-nav pull-xs-right">
					<li class="navbar-label">
						Logged in as {{ user.username }}
					</li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:logout' %}">Log out</a>
                    </li>
                </ul>
            </nav>
        {% endif %}

        <div class="container">
            <div class="row m-t-1">
                <div class="col-md-6 offset-md-3">
                    <h1 class="text-hide page-title">
                        Made Near You
                    </h1>
                </div>
            </div>

            <div class="row m-b-1" role="navigation">
                <div class="col-md-6 offset-md-3">
                    <hr>
                    <ul class="nav nav-inline p-x-1">
                        <li class="nav-item">
                            <a class="nav-link{% if url_name == 'home' %} active{% endif %}" href="{% url 'home' %}">Home</a>
                            <a class="nav-link{% if url_name == 'producers_map' %} active{% endif %}" href="{% url 'producers_map' %}">Find producers</a>
                            <a class="nav-link{% if url_name == 'producer_add' %} active{% endif %}" href="{% url 'producer_add' %}">Add a producer</a>
                            <a class="nav-link{% if url_name == 'about' %} active{% endif %}" href="{% url 'about' %}">About</a>
                        </li>
                    </ul>
                    <hr>
                </div>
            </div>

            <div id="content" tabindex="-1">
                {% block page_title_container %}
                    <div class="row m-b-2">
                        <div class="col-md-6 offset-md-3">
                            <h2>{% block page_title %}{% endblock %}</h2>
                        </div>
                    </div>
                {% endblock page_title_container %}

                {% block content %}
                {% endblock content %}
            </div>

        </div>

    {% block footer %}
        {# Use this if you need to add a visible footer to every page. #}
    {% endblock %}

    {% block foot_extra %}
        {# Use this if you need to add JS etc to the foot of the page. #}
        {% comment %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/js/bootstrap.min.js" integrity="sha384-ux8v3A6CPtOTqOzMKiuo3d/DomGaaClxFYdCu2HPMBEkf6x2xiDyJ7gkXU0MWwaD" crossorigin="anonymous"></script>
        {% endcomment %}
    {% endblock %}
    </body>
</html>

producers/templates/producers/find.html
{% extends 'producers/base.html' %}

{% block title %}Find producer{% endblock %}

{% block page_title %}Find producers near you{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-md-6 offset-md-3">
			
			<form action="" method="post" class="form-inline m-b-3">
				{% csrf_token %}
				<div class="form-group {% if form.postcode.errors %} has-danger{% endif %}">
					<label class="form-control-label" for="id_postcode">
						{{ form.postcode.label }}
					</label>
					{{ form.postcode }}
				</div>
				<button type="submit" class="btn btn-primary">Search</button>

				{% if form.postcode.errors %}
					<span class="p-l-1 text-danger">{{ form.postcode.errors|join:'<br />' }}</span>
				{% endif %}
					
				<div style="display:none;">
					{{ form.honeypot.label }}
					{{ form.honeypot }}
				</div>
			</form>

			{% if postcode %}
				{% if geolocation_error %}
					<p>{{ geolocation_error }}</p>
				{% elif producers|length == 0 %}
					<p>No producers found within {{ max_km }}km of {{ postcode }}.</p>
				{% endif %}
			{% endif %}
		</div> <!-- .col -->
	</div> <!-- .row -->

	{% if postcode and not geolocation_error and producers|length > 0 %}

		<h3>{{ producers|length }} producer{{ producers|length|pluralize }} within {{ max_km }}km of {{ postcode }}</h3>

		{% include 'producers/includes/map.html' with latitude=latitude longitude=longitude producers=producers %}

	{% endif %}

{% endblock content %}

producers/templates/producers/home.html
{% extends 'producers/base.html' %}

{% block head_title %}{{ site_name }}{% endblock %}

{% block page_title_container %}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-6 offset-md-3">

            {{ flatpage.content }}

            {% if producer_list %}
                <h3 class="m-y-2">Recently added producers</h3>
                <dl>
                    {% for producer in producer_list %}
                        <dt><a href="{{ producer.get_absolute_url }}">{{ producer }}, {{ producer.postcode }}</a></dt>
                        <dd>{{ producer.products.all|join:", " }}.</dd>
                    {% endfor %}
                </dl>
            {% endif %}

        </div> <!-- .col -->
    </div> <!-- .row -->
{% endblock content %}

producers/templates/producers/producer_add.html
{% extends 'producers/base.html' %}

{% block title %}Add producer{% endblock %}

{% block page_title %}Add a producer{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-md-6 offset-md-3">
			
			<form action="" method="post" enctype="multipart/form-data">
				<input type="hidden" name="MAX_FILE_SIZE" value="2097152" />
				{% csrf_token %}

				{% for hidden in form.hidden_fields %}
					{{ hidden }}
				{% endfor %}

				{{ form.non_field_errors }}

				<fieldset>
					{% for field in form.visible_fields %}

						{% if field.name == 'products' %}
							<hr class="m-t-0">
							<div class="p-l-1 m-b-2">
								<h3 class="h6">Products{% if field.field.required %} <small class="text-muted">(Required)</small>{% endif %}</h3>
								{% if field.help_text %}
									<p><small class="text-muted">{{ field.help_text }}</small></p>
								{% endif %}
								{% if field.errors %}
									<span class="text-danger">{{ field.errors|join:'<br />' }}</span>
								{% endif %}

								{% for checkbox in field %}
									<div class="checkbox">
										{{ checkbox }}
									</div>
								{% endfor %}
							</div>

						{% elif field.name == 'captcha' %}
							{# We add this manually at the end #}

						{% else %}
							{% include 'producers/includes/form_field.html' %}
						{% endif %}

					{% endfor %}
				</fieldset>

				<hr class="m-t-0">

				<fieldset class="p-l-1 ">
					<h3 class="h6">Images</h3>
					<p><small class="text-muted">Optionally choose one or more images of your products.</small></p>
					
					{% if num_images_submitted %}
						<p class="m-b-0 text-danger">Please choose your image{{ num_images_submitted|pluralize }} again.</p>
						<p class="text-muted"><small>Sorry, images get removed when there are other errors in the form.</small></p>
					{% endif %}

					{{ image_formset.management_form }}

					{% for imgform in image_formset %}
						{% for field in imgform %}
							{# Don't want the 'Delete' checkboxes: #}
							{% if 'DELETE' not in field.id_for_label %}
								{% if field.is_hidden %}
									{{ field }}
								{% else %}
									<p>
										<label id="{{ field.id_for_label">
											{{ field }}
										</label>
									</p>
								{% endif %}
							{% endif %}
						{% endfor %}
					{% endfor %}
				</fieldset>

				<hr class="m-t-0 m-b-2">

				{# Can't seem to get the field to render properly if I just pass that one to the include, so need to cycle through them. Grr. #}
				{% for field in form.visible_fields %}
					{% if field.name == 'captcha' %}
						{% include 'producers/includes/form_field.html' %}
						<hr class="m-t-0 m-b-2">
					{% endif %}
				{% endfor %}
				

				<p class="p-l-1">
					<button type="submit" class="btn btn-primary">Add Producer</button>
				</p>
			</form>
		</div> <!-- .col -->
	</div> <!-- .row -->
{% endblock content %}

producers/templates/producers/producer_detail.html
{% extends 'producers/base.html' %}

{% block title %}{{ producer.business_name }}{% endblock %}

{% block page_title %}{{ producer.business_name }}{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-md-6 offset-md-3">

			<h3>Products</h3>

			<ul>
				{% for product in producer.products.all %}
					<li>{{ product.name }}</li>
				{% endfor %}
			</ul>
			
			<hr>
			
			<h3>Contact details</h3>

			{% if producer.contact_name %}
				<p class="row">
					<span class="col-sm-3">
						<strong>Contact</strong>
					</span>
					<span class="col-sm-9">
						{{ producer.contact_name }}
					</span>
				</p>
			{% endif %}

			{% if producer.phone %}
				<p class="row">
					<span class="col-sm-3">
						<strong>Phone</strong>
					</span>
					<span class="col-sm-9">
						{{ producer.phone }}
					</span>
				</p>
			{% endif %}

			{% if producer.email %}
				<p class="row">
					<span class="col-sm-3">
						<strong>Email</strong>
					</span>
					<span class="col-sm-9">
						<a href="mailto:{{ producer.email }}">{{ producer.email}}</a>
					</span>
				</p>
			{% endif %}

			{% if producer.url %}
				<p class="row">
					<span class="col-sm-3">
						<strong>URL</strong>
					</span>
					<span class="col-sm-9">
						<a href="{{ producer.url }}">{{ producer.url }}</a>
					</span>
				</p>
			{% endif %}

			<hr>

			<h3>Location</h3>

			{% if producer.postcode %}
				<p class="row">
					<span class="col-sm-3">
						<strong>Postcode</strong>
					</span>
					<span class="col-sm-9">
						{{ producer.postcode }}
					</span>
				</p>
			{% endif %}

		</div> <!-- .col -->
	</div> <!-- .row -->


	{% if producer.point %}
		{% include 'producers/includes/map.html' with latitude=producer.latitude longitude=producer.longitude producer=producer %}
	{% endif %}


	{% if producer.images.all|length > 0 %}

		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<hr>

				<h3>Images</h3>

				{% for i in producer.images.all %}
					<p><img class="img-fluid" src="{{ i.image_medium.url }}" width="{{ i.image_medium.width }}" height="{{ i.image_height.height }}"></p>
				{% endfor %}
			</div> <!-- .col -->
		</div> <!-- .row -->
	{% endif %}


{% endblock content %}